### ISSUE TITLE
 Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

### ISSUE THREAD

**Issue by freeozyl80** [ChrisCindy/node-web-console#1]
Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

**Comment by ChrisCindy** [comment]
@freeozyl80 Does it behave normally when you type the same command directly in the real shell? I think maybe the error occured because of the command itself rather than Node-Web-Console. Can you show the command entirely then I can test that on my own machine ?
